language: python
python:
  - 2.7
  - 3.4
cache:
  directories:
    - dante-1.4.1
    - libsodium-1.0.16
sudo: enabled
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential dnsutils iproute nginx bc
  - sudo dd if=/dev/urandom of=/usr/share/nginx/html/file bs=1M count=10
  - sudo sh -c "echo '127.0.0.1    localhost' > /etc/hosts"
  - sudo service nginx restart
  - pip install --upgrade pip
  - pip install coverage pep8 pyflakes nose PySocks cymysql
  - sudo rm -rf ~/build/maxsky/shadowsocksr-manyuser/dante*
  - sudo rm -rf ~/build/maxsky/shadowsocksr-manyuser/libsodium*
  - sudo tests/socksify/install.sh
  - sudo tests/libsodium/install.sh
  - sudo tests/setup_tc.sh
script:
  - tests/jenkins.sh
